/*
Name: Ankit Sharma
Roll Number:mtc1429
Date of Submission:07-Aug-2014
Deadline date:08-Aug-2014
Program description:This program computes the fibonacci number iteratively and recursively corresponding to number n input by user.It also compares the time taken in both strategies.
Acknowledgements:Dennis Ritchie and http://www.geeksforgeeks.org for using time.h.
*/


#include<stdio.h>
#include<time.h>
#include"cs1429-assign1-prog1.h"

/**********************************Global Variable declaration***********************/
 int num = 0;                                   //For user input number. 
 int iter_Computed_Fib = 0;                     //To store the returned fib number from iterative function.
 int rec_Computed_Fib;                          //To store the returned fib number from recursiveve function.
 extern int iter_Fib_Counter; //Variable to keep track of the largest value of n   for which iterative vesion can generate   fibonacci number.
 int i;                   /*counter just for for loop used for printing various function calls stored in function_call_array[]*/




 /**********************************Main starts from here***********************/                  
int main(void){
       int choice;    /*since recursive version takes several minutes to identify the largest n for which it can generate fibonacci number so the user is given choice to press 1 if he/she wants recursive version to identify it.*/
       double iterative_Time_taken = 0;            //To measure time taken by the iterative function.
       double rec_time_taken = 0;                  //To measure time taken by the recursive function.
       printf("\nEnter the number whose corresponding fibonacci number you want.\n");
       scanf("%d",&num); 
       iterative_Time_taken = clock();/*Using clock function defined in time.h header file included above and storing the current time in iterative_Time_taken variable to calculate the time taken by iterative version*/    
       iter_Computed_Fib = iterative_Fib(num);
  
       iterative_Time_taken = clock() - iterative_Time_taken;
       iterative_Time_taken = iterative_Time_taken / CLOCKS_PER_SEC;
       printf("\n\n\t Outputs by Iterative Version\n\n");
       printf("Fibonacci number corresponding to %d computed by iterative version is = %d\n",num,iter_Computed_Fib);
       printf("Time taken by iterative function is ..................................= %f seconds\n",iterative_Time_taken); 
       printf("Largest value of n for which this iterative version can generate fibonacci number is = %d\n\n",(iter_Fib_Counter - 1));
   
       /***********************Here onwards recursive version calls start**********************************/ 
        printf("\n\n\t Outputs by Recursive Version\n\n");
        printf("Wait for sometime untill recursive function completes..\n");
        rec_time_taken = clock(); /*Using same clock function as for iterative version defined in time.h header file included above and storing the current time in iterative_Time_taken variable to calculate the time taken by recursive version*/
        rec_Computed_Fib = recursive_Fib(num);
   
        printf("Fibonacci number corresponding to %d computed by recursive version is = %d\n",num,rec_Computed_Fib);
        printf("Various number of function calls for each interrmediate f(i)");
        print_Function_Calls();         //This function prints the number of function calls used in recursive version for n
        rec_time_taken = clock()-rec_time_taken;
        rec_time_taken = rec_time_taken/CLOCKS_PER_SEC;

        printf("Time taken by recursive version is ...................................= %f seconds\n\n\n",rec_time_taken); 
        printf("Do you want to check the largest fibonacci number that can be generated by recursive version.\n");
        printf("Please note that it may take 2-3 minutes to complete..\n");
        printf("Enter your choice:Press 1 for yes otherwise press any key:\n");
        scanf("%d",&choice);
            if(choice==1){
            largest_Fib_Recursive();
         }
     return;
     
 }

