/*
Name: Ankit Sharma
Roll Number:mtc1429
Date of Submission:07-Aug-2014
Deadline date:08-Aug-2014
Program description:This program computes the fibonacci number iteratively and recursively corresponding to number n input by user.It also compares the time taken in both strategies.
Acknowledgements:Dennis Ritchie and http://www.geeksforgeeks.org for using time.h.
*/
 #include<stdio.h>
 #include"cs1429-assign1-prog1.h"
  int iter_Fib_Counter=0; //Variable to keep track of the largest value of n   for which iterative vesion can generate fibonacci number.
  int function_call_array[]; //Array for storing and then printing number of function calss for each f(i) upto n.
  extern int num;          //User input as declared in the main file.Its is taken as a global variable so that any function can access it.

      /***********************Iterative function for computing fibonacci number.***********************/
    int iterative_Fib(int number){        
       int a = 0,b = 1;                         //Here a and b are temporary variables for adding intermediate fib number
       int fib = 0;                           //To return computed fibonacci number from iterative function.
       int loop_Counter;

         while(fib>=0){ //while loop just for generating the largest number  by this iterative version and obtaining n corresponding to that.
            iter_Fib_Counter++; /*This is the variable which will keep track of value of n corresponding to largest fibonacci number.*/ 
            a=b;
            b=fib;
            fib=a+b;
        }
       a=0;
       b=1;
       fib=0;
       if(number==0)
         return 0;
       for(loop_Counter=0;loop_Counter<number;loop_Counter++){           //Actual fibonacci number generation loop.
                   a = b;
                   b = fib;
                   fib = a+b;
        }

      if(fib<0){                                //If fib is -ve then it means range of int data type is crossed.
        printf("Range overflow.Please try again and enter a smaller number(<=46)\n");
     return;
      }
   return fib;
 }

/***********************To count the no of function calls in recursive function.***********************/
   static int rec_fun_Call_Counter;      //variable for counting number of function calls for n in recursive version.
   int recursive_Fib(int number){        //Recursive function for computing fibonacci number.
       int rec_Fib = 0;                  //To return computed fibonacci number from recursive function.
       rec_fun_Call_Counter++;           //To count the total number of function calls for input number.
         if(number==0){
           function_call_array[0]+=1;
           return 0;
      }
         if(number==1){
           function_call_array[1]+=1;  //Adding 1 each time f(i) is called.here index of call_array[] is used as i in f(i).
           return 1;
      }
         else {
           rec_Fib=recursive_Fib(number-1) + recursive_Fib(number-2);
           function_call_array[number]+=1;
              if(rec_Fib<0){
                printf("Range overflow.Please try again and enter a smaller number(<=46)\n");
                   return;
                  }
       }
    
    return rec_Fib;
 }


/*****Function to print the number of function calls for each i in f(i) stored in array in above taken function by recursive version***/
  void print_Function_Calls(void){
    int loop_counter;   //just a for loop counter;
    printf("Number of function calls made by recursive version = %d\n",rec_fun_Call_Counter);
      for(loop_counter=0;loop_counter<=num;loop_counter++){
          printf("f(%d) = %d\n",loop_counter,function_call_array[loop_counter]);
       }
 }


/*********Function for calculating largest "n" for which fibonacci can be generated by recursive version.****************/
  int largest_Fib_Recursive(){
    int counter=0;                //counter to keep track of the calculated n by recursive function.
    int rec_Value=0;
      while(rec_Value>=0){ 
        rec_Value=recursive_Fib_2(counter);  /*here recursive version is called for generating fibonacci for each n starting from 0.*/
        printf("Calculating...please wait..");
        printf("\nCalculated for n = %d\n",counter);
        counter++;
       }
    printf("Largest value of n for which recursive version can generate fibonacci number is = %d\n\n",(counter-2));
 }


/*This ecursive subroutine is to be used in computing the largest fibonaccni number in immediately above function named 
largest_Fib_Recursive() to return computed fibonacci number from recursive function.we did not use the previous original recursive version to generate the fibonacci number because in that we were stopping just before the range of int crossed.For calculating the largest value for which recursive version can compute,we will need to go beyond the limit and then print the immediately before n.*/
int recursive_Fib_2(int number){        
                                       
  int rec_Fib = 0;                         
  if(number==0)
   return 0;
  if(number==1)
   return 1;
  else 
   rec_Fib=recursive_Fib(number-1) + recursive_Fib(number-2);
   return rec_Fib;
}

                    /*********************************Ends Here****************************************/

